### ISSUE TITLE
Problemas na requisição

### ISSUE THREAD

**Issue by Murilovisque** [DeveloperCielo/Checkout-Cielo#1]
Ola, estou tentando realizar a integração do modulo de pagamento com o checkout cielo, estou seguindo o manual desses link:

http://developercielo.github.io/Checkout-Cielo/#hist%C3%B3rico-de-vers%C3%B5es

https://github.com/DeveloperCielo/Checkout-Cielo

Bom estou enviando a requisicao para o link:

https://cieloecommerce.cielo.com.br/api/public/v1/orders

com o seguinte formato de mensagem em JSON:

String json = "{"
            + "    \"OrderNumber\": \"42\",                        "
            + "    \"SoftDescriptor\": \"Event_\",                 "
            + "    \"Cart\": {                                     "
            + "        \"Discount\": {                             "
            + "            \"Type\": \"\",                         "
            + "            \"Value\": 0                            "
            + "        },                                          "
            + "        \"Items\": [                                "
            + "            {                                       "
            + "                \"Name\": \"David show - Pista\",   "
            + "                \"Description\": \"\",              "
            + "                \"UnitPrice\": 30000,               "
            + "                \"Quantity\": 2,                    "
            + "                \"Type\": \"Service\",              "
            + "                \"Sku\": \"31\",                    "
            + "                \"Weight\": 0                       "
            + "            }                                       "
            + "        ]                                           "
            + "    },                                              "
            + "    \"Shipping\": {                                 "
            + "        \"Type\": \"WithoutShipping\",              "
            + "        \"SourceZipCode\": \"\",                    "
            + "        \"TargetZipCode\": \"\",                    "
            + "        \"Address\": {                              "
            + "            \"Street\": \"\",                       "
            + "            \"Number\": \"\",                       "
            + "            \"Complement\": \"\",                   "
            + "            \"District\": \"\",                     "
            + "            \"City\": \"\",                         "
            + "            \"State\": \"\"                         "
            + "        },                                          "
            + "        \"Services\": [                             "
            + "            {                                       "
            + "                \"Name\": \"\",                     "
            + "                \"Price\": 0,                       "
            + "                \"Deadline\": 0                     "
            + "            }                                       "
            + "        ]                                           "
            + "    },                                              "
            + "    \"Payment\": {                                  "
            + "        \"BoletoDiscount\": 0,                      "
            + "        \"DebitDiscount\": 0                        "
            + "    },                                              "
            + "    \"Customer\": {                                 "
            + "        \"Identity\": 11111111111,                  "
            + "        \"FullName\": \"Diego\",                    "
            + "        \"Email\": \"\",                            "
            + "        \"Phone\": \"\"                             "
            + "    },                                              "
            + "    \"Options\": {                                  "
            + "        \"AntifraudEnabled\": false                 "
            + "    }                                               "
            + "}                                                   ";
       
        URL url = null;
        HttpURLConnection connection = null;
        BufferedReader bufferedReader = null;

        try {
            url = new URL("https://cieloecommerce.cielo.com.br/api/public/v1/orders");

            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.addRequestProperty("MerchantId","meu codigo");
            connection.setRequestProperty("Content-Type","application/json; charset=utf-8");
            connection.setDoOutput(true);

            DataOutputStream jsonRequest = new DataOutputStream(
                    connection.getOutputStream());

            jsonRequest.writeBytes(json);
            jsonRequest.flush();
            jsonRequest.close();

            bufferedReader = new BufferedReader(new InputStreamReader(
                    connection.getInputStream()));

            String responseLine;
            StringBuffer jsonResponse = new StringBuffer();

            while ((responseLine = bufferedReader.readLine()) != null) {
                jsonResponse.append(responseLine);
            }
           
        } catch (Exception e) {
            e.printStackTrace();
        } finally {           
            try {
                if (bufferedReader != null) {
                    bufferedReader.close();
                }
                if (connection != null) {
                    connection.disconnect();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

.Ao tentar efetuar a requisição recebo o erro abaixo, gostaria de saber se a requisição está no formato JSON está certa, tentei passando somente os valores obrigatórios, sem sucesso, tentei também com os parâmetros não obrigatórios, mas em branco.
.Se possível poderia me disser se ao efetuar a requisição automaticamente irá abrir a página do checkout ou se é necessário que chame esse método a partir de um JSP ?
erro:

Server returned HTTP response code: 400 for URL: https://cieloecommerce.cielo.com.br/api/public/v1/orders

Desde de já agradeço,
Murilo.

**Comment by netojoaobatista** [comment]
Olá @Murilovisque,

Você ativou o modo de teste no seu backoffice antes de iniciar os testes de integração?

Além disso, se você estiver enviando o `MerchantId` como enviou no código, então realmente não vai dar certo. O `MerchantId` é a autenticação da sua conta. Sem essa autenticação, você não conseguirá fazer a integração.


> Se possível poderia me disser se ao efetuar a requisição automaticamente irá abrir a página do checkout ou se é necessário que chame esse método a partir de um JSP ?

Assim que você enviar a requisição, você receberá uma resposta HTTP com um JSON. Entre as propriedades do JSON, você encontrará o `CheckoutUrl`. Utilize a URL retornada nessa propriedade para redirecionar seu usuário para o ambiente de pagamento seguro da Cielo.

Abaixo um exemplo de resposta em caso de sucesso de integração:

```json
{
    "Settings": {
        "CheckoutUrl": "https://cieloecommerce.cielo.com.br/transacional/order/index?id=123",
        "Profile": "CheckoutCielo",
        "Version": 1
    }
}
```

Abaixo um exemplo de resposta em caso de erro de integração:

```json
{
    "message":"An error has occurred."
}
```

**Comment by Murilovisque** [comment]
Olá @netojoaobatista 
Então eu já havia ativado o modo de teste no backoffice e cadastrei esse produto no qual estou enviando na requisição.
Eu recebi o MerchandId da cielo só não o informei no issue, mas o estou utilizando na requisição. Cheguei a instalar também os certificados conforme este link do checkout:

https://github.com/DeveloperCielo/Checkout-Cielo/tree/master/source/attachment

Obrigado por tirar a dúvida referente ao redirecionamento do cliente, mas o problema da requisição ainda persiste.

**Comment by Murilovisque** [comment]
Olá @netojoaobatista <https://github.com/netojoaobatista>
Então eu já havia ativado o modo de teste no backoffice e cadastrei esse
produto no qual estou enviando na requisição.
Eu recebi o MerchandId da cielo só não o informei no issue, mas o estou
utilizando na requisição. Cheguei a instalar também os certificados
conforme este link do checkout:

https://github.com/DeveloperCielo/Checkout-Cielo/tree/master/source/attachment

Obrigado por tirar a dúvida referente ao redirecionamento do cliente, mas o
problema da requisição ainda persiste.

Em 23 de junho de 2015 12:45, João Batista Neto <notifications@github.com>
escreveu:

> Olá @Murilovisque <https://github.com/Murilovisque>,
>
> Você ativou o modo de teste no seu backoffice antes de iniciar os testes
> de integração?
>
> Além disso, se você estiver enviando o MerchantId como enviou no código,
> então realmente não vai dar certo. O MerchantId é a autenticação da sua
> conta. Sem essa autenticação, você não conseguirá fazer a integração.
>
> Se possível poderia me disser se ao efetuar a requisição automaticamente
> irá abrir a página do checkout ou se é necessário que chame esse método a
> partir de um JSP ?
>
> Assim que você enviar a requisição, você receberá uma resposta HTTP com um
> JSON. Entre as propriedades do JSON, você encontrará o CheckoutUrl.
> Utilize a URL retornada nessa propriedade para redirecionar seu usuário
> para o ambiente de pagamento seguro da Cielo.
>
> Abaixo um exemplo de resposta em caso de sucesso de integração:
>
> {
>     "Settings": {
>         "CheckoutUrl": "https://cieloecommerce.cielo.com.br/transacional/order/index?id=123",
>         "Profile": "CheckoutCielo",
>         "Version": 1
>     }
> }
>
> Abaixo um exemplo de resposta em caso de erro de integração:
>
> {
>     "message":"An error has occurred."
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DeveloperCielo/Checkout-Cielo/issues/1#issuecomment-114551681>
> .
>



-- 
Murilo Arantes

**Comment by Murilovisque** [comment]
Alguém poderia me ajudar?

**Comment by netojoaobatista** [comment]
Olá @Murilovisque, estou analisando o JSON e seu código Java para ver se identifico o problema. Fiz alguns testes, mas ainda não identifiquei o problema.

**Comment by Murilovisque** [comment]
Olá @netojoaobatista conseguiu descobrir o problema? É que estou precisando muito finalizar essa parte, caso não consiga irei precisar migrar para outra ferramenta para processar os pagamentos.
Obrigado.

**Comment by Murilovisque** [comment]
Olá @netojoaobatista <https://github.com/netojoaobatista> conseguiu
descobrir o problema? É que estou precisando muito finalizar essa parte,
caso não consiga irei precisar migrar para outra ferramenta para processar
os pagamentos.
Obrigado.

Em 24 de junho de 2015 15:48, João Batista Neto <notifications@github.com>
escreveu:

> Olá @Murilovisque <https://github.com/Murilovisque>, estou analisando o
> JSON e seu código Java para ver se identifico o problema. Fiz alguns
> testes, mas ainda não identifiquei o problema.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DeveloperCielo/Checkout-Cielo/issues/1#issuecomment-114978313>
> .
>



-- 
Murilo Arantes

**Comment by joaolenon** [comment]
@Murilovisqu, fiz um request usando seu json e obtive essa resposta:

```json
{
    "message": "The request is invalid.",
    "modelState": {
        "orderViewModel.Cart.Discount.Type": [
            "[Cart.Discount.Type] é obrigatório dado que o valor do desconto foi maior ou igual a zero."
        ],
        "orderViewModel.Shipping.Services[0].Name": [
            "[Shipping.Service.Name] é obrigatório."
        ],
        "orderViewModel.Shipping.Address.Street": [
            "[Shipping.Address.Street] é obrigatório."
        ],
        "orderViewModel.Shipping.Address.Number": [
            "[Shipping.Address.Number] é obrigatório."
        ],
        "orderViewModel.Shipping.Address.District": [
            "[Shipping.Address.District] é obrigatório."
        ],
        "orderViewModel.Shipping.Address.City": [
            "[Shipping.Address.City] é obrigatório."
        ],
        "orderViewModel.Shipping.Address.State": [
            "[Shipping.Address.State] é obrigatório."
        ],
        "orderViewModel.Customer.Phone": [
            "[Customer.Phone] deve conter no mínimo 10 e no máximo 11 caracteres."
        ]
    }
}
```
Usei o  Postman (Rest Client) para fazer request
https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm

Json usado no request:

```json
{
  "OrderNumber": "42",
  "SoftDescriptor": "Event_",
  "Cart": {
    "Discount": {
      "Type": "",
      "Value": 0
    },
    "Items": [
      {
        "Name": "David show - Pista",
        "Description": "",
        "UnitPrice": 30000,
        "Quantity": 2,
        "Type": "Service",
        "Sku": "31",
        "Weight": 0
      }
    ]
  },
  "Shipping": {
    "Type": "WithoutShipping",
    "SourceZipCode": "",
    "TargetZipCode": "",
    "Address": {
      "Street": "",
      "Number": "",
      "Complement": "",
      "District": "",
      "City": "",
      "State": ""
    },
    "Services": [
      {
        "Name": "",
        "Price": 0,
        "Deadline": 0
      }
    ]
  },
  "Payment": {
    "BoletoDiscount": 0,
    "DebitDiscount": 0
  },
  "Customer": {
    "Identity": 11111111111,
    "FullName": "Diego",
    "Email": "",
    "Phone": ""
  },
  "Options": {
    "AntifraudEnabled": false
  }
}
```

**Comment by joaolenon** [comment]
Fiz um request usando o json abaixo e obtive sucesso.

```json
{
  "OrderNumber": "42",
  "SoftDescriptor": "Event_",
  "Cart": {
    "Discount": null,
    "Items": [
      {
        "Name": "David show - Pista",
        "Description": "",
        "UnitPrice": 30000,
        "Quantity": 2,
        "Type": "Service",
        "Sku": "31",
        "Weight": 0
      }
    ]
  },
  "Shipping": {
    "Type": "WithoutShipping",
    "SourceZipCode": "",
    "TargetZipCode": "",
    "Address": {
      "Street": "Av. Paulista",
      "Number": "123",
      "Complement": "",
      "District": "Jardins",
      "City": "Sao Paulo",
      "State": "SP"
    },
    "Services": [
      {
        "Name": "Sedex",
        "Price": 0,
        "Deadline": 0
      }
    ]
  },
  "Payment": {
    "BoletoDiscount": 0,
    "DebitDiscount": 0
  },
  "Customer": {
    "Identity": 11111111111,
    "FullName": "Diego",
    "Email": "",
    "Phone": "91309193113"
  },
  "Options": {
    "AntifraudEnabled": false
  }
}
```

**Comment by Murilovisque** [comment]
Olá João, tudo bem?
Bom, referente ao problema para encaminhar o usuario para o checkout cielo
consegui graças a sua ajuda. Mas agora estou com um outro problema.
O retorno da mudança de status, tentei de diversas formas, porém sem
sucesso. Tentei configurando em meu sistema os serviços responsaveis por
tratar as requisições POST e também no backoffice para as URLs abaixo:

http://murilovisque.ddns.net:8080/Apenkooi/mudan.jsp
http://murilovisque.ddns.net:8080/Apenkooi/x23kdpdkl3js359sh2k4kf

Mas em nenhum dos casos foi registrado uma requisição ao meu sistema. Na
mensagem de erro da cielo também não informa o código de erro HTTP, testei
com o REST CLIENT do firefox e com ele a requisição funciona e meu sistema
a registra.

Conseguiria me ajudar nesse ponto também por favor?

Obrigado

2015-06-25 21:58 GMT-03:00 João Lenon <notifications@github.com>:

> Fiz um request usando o json abaixo e obtive sucesso.
>
> {
>   "OrderNumber": "42",
>   "SoftDescriptor": "Event_",
>   "Cart": {
>     "Discount": null,
>     "Items": [
>       {
>         "Name": "David show - Pista",
>         "Description": "",
>         "UnitPrice": 30000,
>         "Quantity": 2,
>         "Type": "Service",
>         "Sku": "31",
>         "Weight": 0
>       }
>     ]
>   },
>   "Shipping": {
>     "Type": "WithoutShipping",
>     "SourceZipCode": "",
>     "TargetZipCode": "",
>     "Address": {
>       "Street": "Av. Paulista",
>       "Number": "123",
>       "Complement": "",
>       "District": "Jardins",
>       "City": "Sao Paulo",
>       "State": "SP"
>     },
>     "Services": [
>       {
>         "Name": "Sedex",
>         "Price": 0,
>         "Deadline": 0
>       }
>     ]
>   },
>   "Payment": {
>     "BoletoDiscount": 0,
>     "DebitDiscount": 0
>   },
>   "Customer": {
>     "Identity": 11111111111,
>     "FullName": "Diego",
>     "Email": "",
>     "Phone": "91309193113"
>   },
>   "Options": {
>     "AntifraudEnabled": false
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DeveloperCielo/Checkout-Cielo/issues/1#issuecomment-115449151>
> .
>



-- 
Murilo Arantes

**Comment by leandrobh3** [comment]
Reforço o pedido do amigo acima, sobre as URLs de notificações e mudança de status que não estão sendo requisitadas de maneira adequada pelo sistema da Cielo.
Pelo menos em meu sistema, estou monitorando as requisições que são enviadas, e chegam requisições GET sem parâmetros. E logo depois, dispara-se um erro para o e-mail informando que foram enviados os parâmetros. 
Realizando o teste de uma requisição post com os parâmetros informados pelo e-mail de erro, o site aceita a requisição e retorna Ok!
Ou seja, as requisições do sistema da Cielo, com as minhas URLs configuradas, não estão corretas.

**Comment by RailtonSantos** [comment]
Olá, boa tarde Murilo, Neto, João e Leandro, estou com dificuldade para executar a mesma tarefa que o Murilo descreveu, vocês poderia me encaminhar os seus testes?? Ou talvez algum lugar onde eu possa me orientar, por que ainda sou meio leigo e os manuais não estão me ajudando muito.. Valeu!

**Comment by Murilovisque** [comment]
Olá Railton, então referente a integração com a cielo dei uma parada e
voltarei somente em dezembro, mas reforço que não consegui resolver o
problema até então, configurei o backoffice para retornar por um hostname e
pelo IP de minha máquina, sem sucesso, na URL tentei usando outras porta
tipo http://meuhostnameOuIP:8082, sem sucesso, dei uma pesquisa e a
resposta que conclui é que sempre o check-out da cielo vai na porta 80 e
como tava testando redirecionamento pro IP daqui de casa, provavelmente não
ia, o porquê, a provedora de Internet bloqueia essa porta, e não consegui
configurar o roteador para redirecionar a porta 80 de jeito nenhum, mesmo
configurando não ia, se pudéssemos configurar no check-out para outra
porta, talvez desse certo. Bom cara só voltarei a ver isso em dezembro. E
caso consiga algo te envio a resposta, mas por enquanto teria que testar de
algum servidor ou PC que não bloqueie a porta 80. Por favor se eu estiver
enganado me corrijam. Abraço
Em 18/11/2015 1:29 PM, "RailtonSantos" <notifications@github.com> escreveu:

**Comment by leandrobh3** [comment]
@RailtonSantos Qual passo você está? Qual sua dificuldade atualmente?

**Comment by netojoaobatista** [comment]
@RailtonSantos, qual a dificuldade?
