### ISSUE TITLE
Recuperando dados via POST com codeigniter

### ISSUE THREAD

**Issue by ximnes** [DeveloperCielo/Checkout-Cielo#12]
Olá a todos.
Estou com problemas para receber os dados na URL de notificação e de status.

Estou usando o codeigniter, e os dados não fazem update na tabela.
Segue os códigos
Controller Cart.php
	public function notify(){
		$order_number = $this->input->post('order_number');
		$mod_ship = $this->input->post('shipping_type');
		$name_ship = $this->input->post('shipping_name');
		$price_ship = $this->input->post('shipping_price');
		$cep_ship = $this->input->post('shipping_adress_zipcode');
		$dist_ship = $this->input->post('shipping_adress_district');
		$city_ship = $this->input->post('shipping_adress_city');
		$state_ship = $this->input->post('shipping_state');
		$adre_ship1 = $this->input->post('shipping_adress_line1');
		$adre_ship2 = $this->input->post('shipping_adress_line2');
		$number_ship = $this->input->post('shipping_adress_number');
	
						
		$data = array(
			'order_shipping' => $price_ship,
			'order_status' => $this->input->post('payment_status'),
			'order_tid'	=> $this->input->post('tid')
		);

		$myOrder = $this->store_model->upMyOrders($order_number, $data);
		echo '<status>OK</status>';
		$data['status'] = '<status>OK</status>';
		$this->load->view('store/notify', $data);

	}
	public function status(){
		$order_number = $this->input->post('order_number');
		$data = array(
			'order_status' => $this->input->post('payment_status'),
		);

        $myOrder = $this->store_model->upMyOrders($order_number, $data);
		echo '<status>OK</status>';
		$data['status'] = '<status>OK</status>';
		$this->load->view('store/status', $data);
	}

Store_model
		public function upMyOrders($order_number, $data){
			$query = $this->db->where(array('order_number' => $order_number))
							  ->update('tb_store_orders', $data);
		}
		
}

Se alguém puder dar uma luz, já tentei por a variável $data dentro dos models, porém não obtive sucesso também.

**Comment by netojoaobatista** [comment]
Os dados estão chegando na sua aplicação? Se estiverem, então você precisará analisar os logs para ver onde está o erro no seu código. Se os dados não estiverem chegando na aplicação, então você precisa verificar se configurou corretamente as URLs dentro do seu backoffice.
