### ISSUE TITLE
Erro Http403 ao enviar solicitação para o Checkout-Cielo

### ISSUE THREAD

**Issue by afviriato** [DeveloperCielo/Checkout-Cielo#13]
Estabelecimento: 1070535165
MerchantID: 83af5ca6-b5da-4342-8d75-9edf422673bd
CNPJ: 11.137.113/0001-50
TI Sistema

Boa tarde. Meu nome é Alexandre, falo em nome da TI Sistema. Estou tentando realizar a integração do nosso sistema com o chekout-cielo, porém, quando eu envio o post para a url: https://cieloecommerce.cielo.com.br/api/public/v1/orders, estou recebendo um Http 403.
Estou usando Java com Jersey, para enviar o post.
Segue treco do código que realiza o POST:

Código:
---------
 private Settings sendData2Cielo(CieloRequestObject cieloRequestObject) {

        String url        = "https://cieloecommerce.cielo.com.br/api/public/v1/orders";
        String merchantId = "83af5ca6-b5da-4342-8d75-9edf422673bd";

        ClientConfig clientConfig = new DefaultClientConfig();
        clientConfig.getFeatures().put(JSONConfiguration.FEATURE_POJO_MAPPING, Boolean.TRUE);
        Client client = Client.create(clientConfig);

        WebResource webResource = client.resource(url);
        webResource.header("MerchantId", merchantId);
        webResource.header("Content-Type", "application/json; charset=utf-8");
      
        //cieloRequestObject é um objeto que será transformado em JSON, e enviado, seguindo a documentação da cielo
       
        ClientResponse response = webResource.type(MediaType.APPLICATION_JSON).post(ClientResponse.class, cieloRequestObject);

        if (response.getStatus() != 200) {
            throw new RuntimeException("Erro ao conectar com a Cielo" + response.getStatus());
        }

        Settings settings = response.getEntity(Settings.class);
        return settings;
    }
--------
Print to erro:
![captura de tela de 2015-11-12 14_30_58](https://cloud.githubusercontent.com/assets/15876038/11190634/cd25e626-8c7d-11e5-98be-1e5be9d41f87.png)

**Comment by netojoaobatista** [comment]
O erro 403 é causado pelo uso incorreto das credenciais do EC. Verifique se suas credenciais foram definidas corretamente.
