### ISSUE TITLE
Integration Doubts

### ISSUE THREAD

**Issue by 1060486** [DeveloperCielo/Checkout-Cielo#14]
Bom dia,

Por exemplo para os valores payment_method_type e payment_method_brand é indicado que é um numérico, mas que valores podem ser enviados? Se enviarem nesse campo o valor 1 o que significa? E se enviarem o valor 2, e restantes valores?

Em relação ao campo order_number sabemos que é enviado no URL de notificação. É possível para vocês enviarem também o order_number no URL de Retorno?

Obrigado.

Cumprimentos,
Luís Jorge

**Comment by netojoaobatista** [comment]
Luís, 

**Métodos de pagamento** - `payment_method_type`:

|Valor|Descrição|
|-----|---------|
|1|Cartão de Crédito|
|2|Boleto Bancário|
|3|Débito Online|
|4|Cartão de Débito|

**Bandeira** - `payment_method_brand`:

|Valor|Descrição|
|-----|---------|
|1|Visa|
|2|Mastercad|
|3|AmericanExpress|
|4|Diners|
|5|Elo|
|6|Aura|
|7|JCB|

> Em relação ao campo order_number sabemos que é enviado no URL de notificação. É possível para vocês enviarem também o order_number no URL de Retorno?

Nenhum dado é enviado na *URL de Retorno*, apenas na *URL de Notificação*.

**Comment by fabiopaiva** [comment]
Na documentação não tem estas informações e agora preciso também do payment_method_bank que não encontrei

**Comment by netojoaobatista** [comment]
As informações já estão disponíveis na documentação, inclusive `payment_method_bank`.

**Comment by fabiopaiva** [comment]
Aeeee!!!! 
:)

**Comment by 1060486** [comment]
Bom dia,

Relativamente a esta questão "Nenhum dado é enviado na URL de Retorno, apenas na URL de Notificação.", seria possível incluir alguma informação (order_number) neste URL de retorno.

Neste momento e sem informação nenhuma, não temos identificar a reserva / transação de forma a indicar ao cliente se a mesma obteve sucesso ou não.

Obrigado.
