### ISSUE TITLE
payment_method_type e payment_method_brand não são explicitados na documentação

### ISSUE THREAD

**Issue by TiagoGouvea** [DeveloperCielo/Checkout-Cielo#15]
Os possíveis valores e significados destas duas variáveis de retorno não são apresentadas na documentação.

**Comment by netojoaobatista** [comment]
@TiagoGouvea, essa questão foi respondida em #14 e a resposta será consolidada com a adição da informação ao manual. Veja a tabela com os valores em #14 e, se houver mais alguma questão, por favor, me avise.

:smile:

**Comment by TiagoGouvea** [comment]
Ok. Realmente nesta issue você responde a questão, mas no manual disponível atualmente (https://developercielo.github.io/Checkout-Cielo/) não tem esta informação. Será que faltou publicar?

**Comment by TiagoGouvea** [comment]
Excelente. Grato @netojoaobatista
