### ISSUE TITLE
Integração  C# erro 404

### ISSUE THREAD

**Issue by HDio** [DeveloperCielo/Checkout-Cielo#17]
Preciso muito finalizar essa integração alguém pode me ajuda?

Estou com seguinte problema, ao realizar o post me deparo com seguinte erro: 
 
![image](https://cloud.githubusercontent.com/assets/17024835/12782747/64d8b2cc-ca64-11e5-8de6-5fb97a1f35fb.png)

Abaixo o meu código:

        HttpWebRequest request = (HttpWebRequest)

        WebRequest.Create("https://cieloecommerce.cielo.com.br/api/public/v1/orders");

        request.MediaType = "application/json";
        request.Method = "POST";
        request.Headers ["Type"] = "application/json";
        request.ContentType = "application/json";
        request.Headers["MerchantId"] = "dc68fd60-01ba-4d70-9ae2-a2c8c281bc48";

string json = "{"
            + "    \"OrderNumber\": \"12344\","
            + "    \"SoftDescriptor\": \"Nome que aparecerá na fatura\","
            + "    \"Cart\": {"
            + "        \"Discount\": {"
            + "            \"Type\": \"Percent\","
            + "            \"Value\": 10"
            + "        },"
            + "        \"Items\": ["
            + "            {"
            + "                \"Name\": \"Nome do produto\","
            + "                \"Description\": \"Descrição do produto\","
            + "                \"UnitPrice\": 100,"
            + "                \"Quantity\": 2,"
            + "                \"Type\": \"Asset\","
            + "                \"Sku\": \"Sku do item no carrinho\","
            + "                \"Weight\": 200"
            + "            }"
            + "        ]"
            + "    },"
            + "    \"Shipping\": {"
            + "        \"Type\": \"Correios\","
            + "        \"SourceZipCode\": \"14400000\","
            + "        \"TargetZipCode\": \"11000000\","
            + "        \"Address\": {"
            + "            \"Street\": \"Endereço de entrega\","
            + "            \"Number\": \"123\","
            + "            \"Complement\": \"\","
            + "            \"District\": \"Bairro da entrega\","
            + "            \"City\": \"Cidade de entrega\","
            + "            \"State\": \"SP\""
            + "        },"
            + "        \"Services\": ["
            + "            {"
            + "                \"Name\": \"Serviço de frete\","
            + "                \"Price\": 123,"
            + "                \"Deadline\": 15"
            + "            }"
            + "        ]"
            + "    },"
            + "    \"Payment\": {"
            + "        \"BoletoDiscount\": 0,"
            + "        \"DebitDiscount\": 10"
            + "     },"
            + "     \"Customer\": {"
            + "         \"Identity\": 11111111111,"
            + "         \"FullName\": \"Fulano Comprador da Silva\","
            + "         \"Email\": \"fulano@email.com\","
            + "         \"Phone\": \"11999999999\""
            + "     },"
            + "     \"Options\": {"
            + "         \"AntifraudEnabled\": false"
            + "     }"
            + "}";

       using (var writer = new StreamWriter(request.GetRequestStream()))
        {

            writer.Write(json);
            writer.Close();
        }

        try{

        HttpWebResponse response = (HttpWebResponse) 

         request.GetResponse();
        }

        catch (Exception)
        {
        }
    }

**Comment by HelcioNosWeb** [comment]
Ola HDio,

**Comment by HDio** [comment]
opa pode me ajudar Helcio?

**Comment by HelcioNosWeb** [comment]
Vou deixar meu código que está funcionando aqui pra você dar uma olhada e ver se ajuda. Lembrando que para usá-lo, você terá que instalar o Json.NET no seu projeto (dá pra fazer pelo NUGET). Segue meu código:

        private void ExecutaCielo(DadosDoPedido _Pedido)
        {
            try
            {
                NosWebCoreCielo _ConfigCielo = db.NosWebCoreCielos.FirstOrDefault();

                var httpWebRequest = (HttpWebRequest)WebRequest.Create(_ConfigCielo.UrlCielo);
                httpWebRequest.Headers["MerchantId"] = _ConfigCielo.MerchantID;
                httpWebRequest.ContentType = "application/json";
                httpWebRequest.Method = WebRequestMethods.Http.Post;
                httpWebRequest.Timeout = 70000;

                using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
                {
                    _DadosSite = db.NosWebCoreDadosSites.FirstOrDefault();
                    NosWebCoreEnderecoEntrega enderecoEntrega = new NosWebCoreEnderecoEntrega();

                    if (_Pedido.EnderecoEntregaID > 0)
                    {
                        enderecoEntrega = db.NosWebCoreEnderecoEntregas.Where(x => x.EnderecoEntregaID == _Pedido.EnderecoEntregaID).FirstOrDefault();
                    }

                    NosWebCoreUsuario cliente = db.NosWebCoreUsuarios.Where(x => x.UsuarioID == _Pedido.UsuarioID).FirstOrDefault();
                    List<NosWebCoreItensPedido> _ItensPedidoCollection = db.NosWebCoreItensPedidos.Where(x => x.CodigoPedido == _Pedido.CodigoPedido).ToList();
                    string SoftDescriptor = ""; // até 13 caracteres
                    string FormaEnvio = "FixedAmount"; // Tipo do frete: “Correios”, “FixedAmount”, “Free”, “WithoutShippingPickUp”, “WithoutShipping”.
                    string cpfOuCnpj = string.Empty;
                    string AntifraudEnabled = "true";  // Boolean. TRUE=Transação será analisada pelo anti-fraude, FALSE=Transação NÃO será analisada pelo anti-fraude
                    string BoletoDiscount = "0"; // até 3 caracteres. Desconto, em porcentagem, para pagamentos a serem realizados com boleto. Aceita Zero
                    string DebitDiscount = "0"; // até 3 caracteres. Desconto, em porcentagem, para pagamentos a serem realizados com débito online. Aceita Zero

                    if (_ConfigCielo.BoletoDiscount != null)
                    {
                        BoletoDiscount = _ConfigCielo.BoletoDiscount.ToString();
                    }

                    if (_ConfigCielo.DebitDiscount != null)
                    {
                        DebitDiscount = _ConfigCielo.DebitDiscount.ToString();
                    }

                    if (_ConfigCielo.AntiFraudEnabled == true)
                    {
                        AntifraudEnabled = "true";
                    }
                    else
                    {
                        AntifraudEnabled = "false";
                    }

                    string ServiceName = _Pedido.FormaDeEnvio;  // até 128 caracteres. Nome do serviço de frete.
                    string ServicePrice = "0";  // até 18 caracteres. Preço do serviço de frete (em centavos. Ex: R$ 1,00 = 100).
                    string ServiceDeadLine = "1";  // Numérico até 9 caracteres. Prazo de entrega (em dias).

                    if (_Pedido.Frete != null && _Pedido.Frete > 0)
                    {
                        ServicePrice = Convert.ToString(_Pedido.Frete).Replace(".", "").Replace(",", "");  // até 18 caracteres. Preço do serviço de frete (em centavos. Ex: R$ 1,00 = 100).
                    }

                    string discountType = "Amount"; // Tipo do desconto a ser aplicado: "Amount”, “Percent”. Obrigatório caso Value for maior ou igual a zero.
                    string discountValue = "0"; // até 18 caracteres. Valor do desconto a ser aplicado (pode ser valor absoluto ou percentual). Obrigatório caso Type for “Amount” ou “Percent”.

                    if (_Pedido.ValorDesconto > 0)
                    {
                        discountValue = Convert.ToString(_Pedido.ValorDesconto).Replace(".", "").Replace(",", "");
                    }

                    if (!string.IsNullOrEmpty(cliente.CPF))
                    {
                        string clearCPF = string.Empty;
                        // Limpa o CPF
                        clearCPF = cliente.CPF.Trim(); // Elimina Espaços em Branco
                        clearCPF = clearCPF.Replace("-", ""); // Remove Separador de Dígito Verificador
                        clearCPF = clearCPF.Replace(".", ""); // Remove os Separadores das Casas

                        cpfOuCnpj = clearCPF;
                    }
                    else
                    {
                        string clearCnpj = string.Empty;
                        // Limpa o CNPJ
                        clearCnpj = cliente.CNPJ.Trim(); // Elimina Espaços em Branco
                        clearCnpj = clearCnpj.Replace("-", ""); // Remove Separador de Dígito Verificador
                        clearCnpj = clearCnpj.Replace(".", ""); // Remove os Separadores das Casas
                        clearCnpj = clearCnpj.Replace("/", ""); // Remove os Separadores das Casas

                        cpfOuCnpj = clearCnpj;
                    }

                    string desconto = "        \"Discount\": {"
                            + "            \"Type\": \"" + discountType + "\"," // Tipo do desconto a ser aplicado: "Amount”, “Percent”. Obrigatório caso Value for maior ou igual a zero.
                            + "            \"Value\": " + discountValue + "" // até 18 caracteres. Valor do desconto a ser aplicado (pode ser valor absoluto ou percentual). Obrigatório caso Type for “Amount” ou “Percent”.
                            + "        },";

                    string itensCarrinho = "        \"Items\": [";

                    int itemNumber = 1;
                    foreach (var item in _ItensPedidoCollection)
                    {
                        string peso = "1";

                        //if (item.Peso > 0)
                        //{
                        //    peso = item.Peso.ToString();
                        //}

                        if (itemNumber == _ItensPedidoCollection.Count)
                        {
                            itensCarrinho +=
                            "            {"
                            + "                \"Name\": \"" + item.NomeProduto + "\"," // até 128 caracteres, Nome do item no carrinho.
                            + "                \"Description\": \"" + item.NomeProduto + "\"," // até 256 caracteres. Descrição do item no carrinho.
                            + "                \"UnitPrice\": " + item.Preco.ToString().Replace(".", "").Replace(",", "") + "," // até 18 caracteres. Preço unitário do item no carrinho (em centavos.* Ex: R$ 1,00 = 100)*.
                            + "                \"Quantity\": " + item.Quantidade + "," // até 9 caracteres. Quantidade do item no carrinho.
                            + "                \"Type\": \"Asset\"," // Alphanumeric. Tipo do item no carrinho. Asset=Material físico, Digital=Produtos Digitais, Service=Serviços, Payment=Outros pagamentos
                            + "                \"Sku\": \"" + item.CodigoRefProduto + "\"," // até 32 caracteres. Sku do item no carrinho.
                            + "                \"Weight\": " + peso + "" // até 9 caracteres. Em gramas (ex: 1 Kg = 1000 gramas). Obrigatório ser maior que zero.
                            + "            }"
                            + "        ]";
                        }
                        else
                        {
                            itensCarrinho +=
                            "            {"
                            + "                \"Name\": \"" + item.NomeProduto + "\"," // até 128 caracteres, Nome do item no carrinho.
                            + "                \"Description\": \"" + item.NomeProduto + "\"," // até 256 caracteres. Descrição do item no carrinho.
                            + "                \"UnitPrice\": " + item.Preco.ToString().Replace(".", "").Replace(",", "") + "," // até 18 caracteres. Preço unitário do item no carrinho (em centavos.* Ex: R$ 1,00 = 100)*.
                            + "                \"Quantity\": " + item.Quantidade + "," // até 9 caracteres. Quantidade do item no carrinho.
                            + "                \"Type\": \"Asset\"," // Alphanumeric. Tipo do item no carrinho. Asset=Material físico, Digital=Produtos Digitais, Service=Serviços, Payment=Outros pagamentos
                            + "                \"Sku\": \"" + item.CodigoRefProduto + "\"," // até 32 caracteres. Sku do item no carrinho.
                            + "                \"Weight\": " + peso + "" // até 9 caracteres. Em gramas (ex: 1 Kg = 1000 gramas). Obrigatório ser maior que zero.
                            + "            },";
                        }

                        itemNumber++;
                    }

                    string carrinho = "{" + desconto + itensCarrinho + "    },";




                    string json = "{"
                            + "    \"OrderNumber\": \"" + _Pedido.PedidoNumero + "\"," // até 64 caracteres
                            + "    \"SoftDescriptor\": \"" + SoftDescriptor + "\"," // até 64 caracteres
                            + "    \"Cart\": " + carrinho + ""
                            + "    \"Shipping\": {"
                            + "        \"Type\": \"" + FormaEnvio + "\"," // até 64 caracteres
                            + "        \"SourceZipCode\": \"" + _DadosSite.CepOrigemDaEntrega.Replace("-", "") + "\","; // 8 caracteres

                    if (enderecoEntrega != null && _Pedido.EnderecoEntregaID > 0)
                    {
                        json +=
                            "        \"TargetZipCode\": \"" + enderecoEntrega.Cep.Replace("-", "") + "\"," // 8 caracteres
                            + "        \"Address\": {"
                            + "            \"Street\": \"" + enderecoEntrega.Endereco + "\"," // até 256 caracteres. Rua, avenida, travessa, etc, do endereço de entrega do comprador.
                            + "            \"Number\": \"" + enderecoEntrega.Numero + "\"," // até 8 caracteres. Número do endereço de entrega do comprador.
                            + "            \"Complement\": \"" + enderecoEntrega.Complemento + "\"," // até 256 caracteres. Complemento do endereço de entrega do comprador.
                            + "            \"District\": \"" + enderecoEntrega.Bairro + "\"," // até 64 caracteres. Bairro do endereço de entrega do comprador.
                            + "            \"City\": \"" + enderecoEntrega.Cidade + "\"," // até 64 caracteres. Cidade do endereço de entrega do comprador.
                            + "            \"State\": \"" + enderecoEntrega.Estado + "\"" // 2 caracteres. Estado (UF) do endereço de entrega do comprador.
                            + "        },";
                    }
                    else
                    {
                        json +=
                            "        \"TargetZipCode\": \"" + cliente.CEP.Replace("-", "") + "\"," // 8 caracteres
                            + "        \"Address\": {"
                            + "            \"Street\": \"" + cliente.Endereco + "\"," // até 256 caracteres. Rua, avenida, travessa, etc, do endereço de entrega do comprador.
                            + "            \"Number\": \"" + cliente.Numero + "\"," // até 8 caracteres. Número do endereço de entrega do comprador.
                            + "            \"Complement\": \"" + cliente.Complemento + "\"," // até 256 caracteres. Complemento do endereço de entrega do comprador.
                            + "            \"District\": \"" + cliente.Bairro + "\"," // até 64 caracteres. Bairro do endereço de entrega do comprador.
                            + "            \"City\": \"" + cliente.Cidade + "\"," // até 64 caracteres. Cidade do endereço de entrega do comprador.
                            + "            \"State\": \"" + cliente.Estado + "\"" // 2 caracteres. Estado (UF) do endereço de entrega do comprador.
                            + "        },";
                    }

                    json += "        \"Services\": ["
                            + "            {"
                            + "                \"Name\": \"" + ServiceName + "\"," // até 128 caracteres. Nome do serviço de frete.
                            + "                \"Price\": " + ServicePrice + "," // até 18 caracteres. Preço do serviço de frete (em centavos. Ex: R$ 1,00 = 100).
                            + "                \"Deadline\": " + ServiceDeadLine + "" // Numérico até 9 caracteres. Prazo de entrega (em dias).
                            + "            }"
                            + "        ]"
                            + "    },"
                            + "    \"Payment\": {"
                            + "        \"BoletoDiscount\": " + BoletoDiscount + "," // até 3 caracteres. Desconto, em porcentagem, para pagamentos a serem realizados com boleto.
                            + "        \"DebitDiscount\": " + DebitDiscount + "" // até 3 caracteres. Desconto, em porcentagem, para pagamentos a serem realizados com débito online.
                            + "     },"
                            + "     \"Customer\": {"
                            + "         \"Identity\": \"" + cpfOuCnpj + "\"," // até 14 caracteres. CPF ou CNPJ do comprador.                            
                            + "         \"FullName\": \"" + cliente.Nome.Replace("  ", " ") + "\"," // até 288 caracteres. Nome completo do comprador.
                            + "         \"Email\": \"" + cliente.Email + "\"," // até 64 caracteres. Email do comprador.
                            + "         \"Phone\": \"" + cliente.DDDTelefone + cliente.Telefone.Replace("-", "") + "\"" // até 11 caracteres. Telefone do comprador.
                            + "     },"
                            + "     \"Options\": {"
                            + "         \"AntifraudEnabled\": " + AntifraudEnabled + "" // Boolean. TRUE=Transação será analisada pelo anti-fraude, FALSE=Transação NÃO será analisada pelo anti-fraude
                            + "     }"
                            + "}";                    

                    streamWriter.Write(json);
                    streamWriter.Flush();
                    streamWriter.Close();
                }

                var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
                using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                {
                    var result = streamReader.ReadToEnd();

                    Dictionary<string, object> values = deserializeToDictionary(result);

                    string checkoutUrl = GetRedirectUrlCielo(result);

                    Response.Redirect(checkoutUrl);
                }
            }
            catch (Exception ex)
            {
                // se retornar a mensagem: The remote server returned an error: (400) Bad Request.
                // verificar a quantidade de caracteres nos campos que foram enviados.

                string erro = ex.Message;

                if (!ex.Message.Contains("Thread was being aborted"))
                {
                    Geral.EnviaEmailDeErro(string.Format("Erro no código do método ExecutaCielo()<br />{0}", erro), Request.Url.ToString());
                }
            }
        }

        private Dictionary<string, object> deserializeToDictionary(string jo)
        {
            var values = JsonConvert.DeserializeObject<Dictionary<string, object>>(jo);
            var values2 = new Dictionary<string, object>();
            foreach (KeyValuePair<string, object> d in values)
            {
                if (d.Value is JObject)
                {
                    values2.Add(d.Key, deserializeToDictionary(d.Value.ToString()));
                }
                else
                {
                    values2.Add(d.Key, d.Value);
                }
            }
            return values2;
        }

        private string GetRedirectUrlCielo(string result)
        {
            var values = JsonConvert.DeserializeObject<Dictionary<string, object>>(result);
            var values2 = new Dictionary<string, object>();
            foreach (KeyValuePair<string, object> d in values)
            {
                if (d.Value is JObject)
                {
                    values2.Add(d.Key, deserializeToDictionary(d.Value.ToString()));

                    if (d.Key == "settings")
                    {
                        foreach (KeyValuePair<string, object> x in deserializeToDictionary(d.Value.ToString()))
                        {
                            if (x.Key == "checkoutUrl")
                            {
                                return x.Value.ToString();
                            }
                        }
                    }
                }
                else
                {
                    values2.Add(d.Key, d.Value);
                }


            }

            return string.Empty;
        }

**Comment by HDio** [comment]
obrigado vou testar aqui.

**Comment by HDio** [comment]
Helcio to perdido, continua dando erro. eu preciso enviar esses paramentros aqui tbm? acho que pode ser isso que está faltando:

"CheckoutUrl": "https://cieloecommerce.cielo.com.br/transacional/order/index?id=123",
    "Profile": "CheckoutCielo",
    "Version": 1


se for isso pode explicar como envio?

**Comment by HDio** [comment]
Ainda continua com problema, alguém pode me ajudar?

**Comment by HDio** [comment]
Enfim consegui corrigir, muito obrigado, agora pode me orientar a como pegar a url de retorno de status? sou novo em programação e estou bastante perdido. Desde já agradeço"

**Comment by netojoaobatista** [comment]
Essa URL é cadastrada no Backoffice, como descrito no manual, na seção [URLs do Checkout Cielo](https://developercielo.github.io/Checkout-Cielo/#urls-do-checkout-cielo)

Basta cadastrar uma URL da sua aplicação e, então, tratar os dados da notificação. Os campos da notificação de status estão descritos na seção [URL de Notificação](https://developercielo.github.io/Checkout-Cielo/#url-de-notificação) do manual de integração.

**Comment by HDio** [comment]
entendi, porém minha dificuldade é desenvolver um metodo que captura essas informações na pagina.

**Comment by HDio** [comment]
teria como me orientar a pegar esse post? só preciso disso o método de manipular essas informações eu sei. Grato

**Comment by netojoaobatista** [comment]
Você vai pegar esses dados da mesma forma como pegaria os dados de um formulário de contato, por exemplo; o formato é exatamente o mesmo.

**Comment by HDio** [comment]
vamos ver se eu entendi, nesse caso no carregamento da pagina e coloco a função request.form["checkout_cielo_order_number"] por exemplo para pegar essa informação?

**Comment by netojoaobatista** [comment]
E depois que tratar as informações, você responde com `<status>OK</status>` para avisar que recebeu a notificação e tratou os dados.

**Comment by HDio** [comment]
beleza, vou tentar primeiramente pegar esse retorno. muito obrigado!

**Comment by HelcioNosWeb** [comment]
Que bom que conseguiu HDio,
Não deu pra responder antes, mas agora vou deixar aqui pra tentar faciliar pra você o meu código de retorno. Vê ae se dá uma clareada:

HTML:
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CieloNotificacao.aspx.cs" Inherits="NosWebCoreBasic.aspx.CieloNotificacao" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <status>OK</status>
    </div>
    </form>
</body>
</html>




CS:
public class DadosRetorno
        {
            public string checkout_cielo_order_number { get; set; }
            public string amount { get; set; }
            public string order_number { get; set; }
            public string created_date { get; set; }
            public string customer_name { get; set; }
            public string customer_identity { get; set; }
            public string customer_email { get; set; }
            public string customer_phone { get; set; }
            public string discount_amount { get; set; }
            public string shipping_type { get; set; }
            public string shipping_name { get; set; }
            public string shipping_price { get; set; }
            public string shipping_address_zipcode { get; set; }
            public string shipping_address_district { get; set; }
            public string shipping_address_city { get; set; }
            public string shipping_address_state { get; set; }
            public string shipping_address_line1 { get; set; }
            public string shipping_address_line2 { get; set; }
            public string shipping_address_number { get; set; }
            public string payment_method_type { get; set; }
            public string payment_method_brand { get; set; }
            public string payment_method_bank { get; set; }
            public string payment_maskedcredicard { get; set; }
            public string payment_installments { get; set; }
            public string payment_antifrauderesult { get; set; }
            public string payment_boletonumber { get; set; }
            public string payment_boletoexpirationdate { get; set; }
            public string payment_status { get; set; }
            public string tid { get; set; }
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (Request.HttpMethod == "POST")
            {                
                //o método POST indica que a requisição é o retorno da validação NPI.
                DadosRetorno _DadosRetorno = new DadosRetorno();

                _DadosRetorno.checkout_cielo_order_number = Request.Form["checkout_cielo_order_number"];
                _DadosRetorno.amount = Request.Form["amount"];
                _DadosRetorno.order_number = Request.Form["order_number"];
                _DadosRetorno.created_date = Request.Form["created_date"];
                _DadosRetorno.customer_name = Request.Form["customer_name"];
                _DadosRetorno.customer_identity = Request.Form["customer_identity"];
                _DadosRetorno.customer_email = Request.Form["customer_email"];
                _DadosRetorno.customer_phone = Request.Form["customer_phone"];
                _DadosRetorno.discount_amount = Request.Form["discount_amount"];
                _DadosRetorno.shipping_type = Request.Form["shipping_type"];
                _DadosRetorno.shipping_name = Request.Form["shipping_name"];
                _DadosRetorno.shipping_price = Request.Form["shipping_price"];
                _DadosRetorno.shipping_address_zipcode = Request.Form["shipping_address_zipcode"];
                _DadosRetorno.shipping_address_district = Request.Form["shipping_address_district"];
                _DadosRetorno.shipping_address_city = Request.Form["shipping_address_city"];
                _DadosRetorno.shipping_address_state = Request.Form["shipping_address_state"];
                _DadosRetorno.shipping_address_line1 = Request.Form["shipping_address_line1"];
                _DadosRetorno.shipping_address_line2 = Request.Form["shipping_address_line2"];
                _DadosRetorno.shipping_address_number = Request.Form["shipping_address_number"];
                _DadosRetorno.payment_method_type = Request.Form["payment_method_type"];
                _DadosRetorno.payment_method_brand = Request.Form["payment_method_brand"];
                _DadosRetorno.payment_method_bank = Request.Form["payment_method_bank"];
                _DadosRetorno.payment_maskedcredicard = Request.Form["payment_maskedcredicard"];
                _DadosRetorno.payment_installments = Request.Form["payment_installments"];
                _DadosRetorno.payment_antifrauderesult = Request.Form["payment_antifrauderesult"];
                _DadosRetorno.payment_boletonumber = Request.Form["payment_boletonumber"];
                _DadosRetorno.payment_boletoexpirationdate = Request.Form["payment_boletoexpirationdate"];
                _DadosRetorno.payment_status = Request.Form["payment_status"];
                _DadosRetorno.tid = Request.Form["tid"];				
                
            }
            else if (Request.HttpMethod == "GET")
            {
                
            }            
        }

**Comment by HDio** [comment]
Helcio eu tentei pegar a url mas não está dando certo com certeza é um detalhe que falta, peguei seu cogido do aps.cs coloquei na minha page load  e no site da cielo coloquei a mesma pagina que uso de retorno para notificação, pois assim quando regresso para a pagina pegar mas não está funcionando, continuo recebendo dezenas de emails da cielo com falha no envio de post de notificação.

to desesperado já.

**Comment by HelcioNosWeb** [comment]
Olá HDio,

Você colocou a tag <status>OK</status> dentro da tag body da sua pagina .aspx?

Como disse o netojoaobatista tem que ter essa tag se não dá erro mesmo.

**Comment by HelcioNosWeb** [comment]
não sei como coloca-se aqui os códigos em HTML, Não aparece. A tag chama-se status igual ao que o netojoaobatista escreveu lá no outro comment

**Comment by HDio** [comment]
entendi, porém para eu responder como retorno, preciso pegar as informações que a cielo me envia no caso a url de notificação, é isso que não consigo. fiz o pagamento em seguida sou redirecionado para a pagina que setei e nela com coloquei uma label pra certificar que recebi a notificação da cielo da uma olhada: mandei o cliente, pra cielo ele efetuou o pagamento tudo ok, agora volta por site e preciso das informações que foi feito o pagamento com sucesso pra atualizar no meu banco. é nesse momento que eu travo.

 if (Request.HttpMethod == "POST")
        {
            //o método POST indica que a requisição é o retorno da validação NPI.
            RetornoCielo retornoCielo = new RetornoCielo();

            retornoCielo.checkout_cielo_order_number = Request.Form["checkout_cielo_order_number"];
            retornoCielo.amount = Request.Form["amount"];
            retornoCielo.order_number = Request.Form["order_number"];
            retornoCielo.created_date = Request.Form["created_date"];
            retornoCielo.customer_name = Request.Form["customer_name"];
            retornoCielo.customer_identity = Request.Form["customer_identity"];
            retornoCielo.customer_email = Request.Form["customer_email"];
            retornoCielo.customer_phone = Request.Form["customer_phone"];
            retornoCielo.discount_amount = Request.Form["discount_amount"];
            retornoCielo.shipping_type = Request.Form["shipping_type"];
            retornoCielo.shipping_name = Request.Form["shipping_name"];
            retornoCielo.shipping_price = Request.Form["shipping_price"];
            retornoCielo.shipping_address_zipcode = Request.Form["shipping_address_zipcode"];
            retornoCielo.shipping_address_district = Request.Form["shipping_address_district"];
            retornoCielo.shipping_address_city = Request.Form["shipping_address_city"];
            retornoCielo.shipping_address_state = Request.Form["shipping_address_state"];
            retornoCielo.shipping_address_line1 = Request.Form["shipping_address_line1"];
            retornoCielo.shipping_address_line2 = Request.Form["shipping_address_line2"];
            retornoCielo.shipping_address_number = Request.Form["shipping_address_number"];
            retornoCielo.payment_method_type = Request.Form["payment_method_type"];
            retornoCielo.payment_method_brand = Request.Form["payment_method_brand"];
            retornoCielo.payment_method_bank = Request.Form["payment_method_bank"];
            retornoCielo.payment_maskedcredicard = Request.Form["payment_maskedcredicard"];
            retornoCielo.payment_installments = Request.Form["payment_installments"];
            retornoCielo.payment_antifrauderesult = Request.Form["payment_antifrauderesult"];
            retornoCielo.payment_boletonumber = Request.Form["payment_boletonumber"];
            retornoCielo.payment_boletoexpirationdate = Request.Form["payment_boletoexpirationdate"];
            retornoCielo.payment_status = Request.Form["payment_status"];
            retornoCielo.tid = Request.Form["tid"];

            //if (retornoCielo.customer_name != null)
            //    lblMensagem0.Text = retornoCielo.customer_name;
            lblMensagem0.Text = Request.QueryString["payment_status"];

        }
        else if (Request.HttpMethod == "GET")
        {

        }

**Comment by HDio** [comment]
desfiz meu codigo e peguei o seu se não se importa para teste para acompanhar o raciocínio melhor.

**Comment by aaluiz** [comment]
Bom dia,
Estou tento o exato mesmo problema desta issue. Estamos usando Asp.NET. A url de retorno está cadastrada no Backoffice, como descrito no manual, na seção URLs do Checkout Cielo. Contudo, ao debugar a página de notificação a requisição que chega até o server é de um comando GET, o que torna impossível acessar os dados do post.
Haveria, algum detalhe que está faltando para essa parte funcionar? Estou utilizando o código disponibilizado pelo HDio e mesmo assim não está funcionando. 
Att.
