### ISSUE TITLE
Notification Content-Type

### ISSUE THREAD

**Issue by eduardohahn** [DeveloperCielo/Checkout-Cielo#18]
Pessoal,

Alguém poderia me informar qual o Content-Type utilizado no POST de notificações?
Estou tendo problemas no recebimento de notificações na minha aplicação (Códigos de status HTTP 0 e 2 no email informativo de erro da Cielo).

Testei com um comando de POST externo utilizando o Content-Type "application/x-www-form-urlencoded" e a minha aplicação retorna status 200 corretamente.

**Comment by netojoaobatista** [comment]
@eduardohahn, você está respondendo ao POST com `<status>OK</status>`?

**Comment by eduardohahn** [comment]
@netojoaobatista, sim segue abaixo o print com o retorno do post

![image](https://cloud.githubusercontent.com/assets/16307204/13644922/07b61c38-e607-11e5-9103-14d2221d76a7.png)

**Comment by netojoaobatista** [comment]
Qual o conteúdo da aba `Request headers`?

**Comment by eduardohahn** [comment]
Segue abaixo:

![image](https://cloud.githubusercontent.com/assets/16307204/13645328/36f4c268-e609-11e5-8ba7-c61e1e783b0d.png)

**Comment by netojoaobatista** [comment]
Certo.

O Content-Type é `application/x-www-form-urlencoded` mesmo. Você está com o modo de teste ativo?

**Comment by eduardohahn** [comment]
Sim, estou em modo de teste.

**Comment by eduardohahn** [comment]
Pelo que verifiquei estou recebendo a requisição sem os valores das variáveis.
Ex.: o parâmetro "payment_status" está vindo nulo.

**Comment by netojoaobatista** [comment]
Estou confirmando aqui, mas acho que o POST de Notificação precisa estar com o modo de teste **des*ativado para funcionar.

**Comment by eduardohahn** [comment]
Se for confirmada essa informação, seria impossível validar as notificações antes de colocar em produção então?

**Comment by netojoaobatista** [comment]
@eduardohahn,

Acabei de ter uma resposta sobre essa questão. A notificação **funciona sim**  no modo de teste, porém houve um problema que estava causando esse erro. A correção já providenciada e estará disponível ainda essa semana.

:smile:

**Comment by eduardohahn** [comment]
Perfeito @netojoaobatista , vou aguardar a liberação e depois retorno o resultado do teste.

Obrigado.

**Comment by netojoaobatista** [comment]
Perfeito!

Fecharei essa issue; caso volte a ter problemas, sinta-se a vontade para reabri-la.

;)

**Comment by eduardohahn** [comment]
Boa tarde @netojoaobatista 
Fiz um teste ontem e ainda recebo mensagem de erro na notificação em modo teste. Consegue verificar por favor se a correção foi aplicada?

Obrigado!
