### ISSUE TITLE
Url de Retorno - Order Number

### ISSUE THREAD

**Issue by 1060486** [DeveloperCielo/Checkout-Cielo#19]
Bom dia,

É possível que vocês acrescentem no Url de retorno o valor do order_number, de forma a conseguirmos identificar a transação corretamente?

Obrigado.

Cumprimentos,
Luís Jorge

**Comment by netojoaobatista** [comment]
Luis, a Cielo não envia nenhum dado para a URL de retorno; você poderá fazer a identificação da transação na URL de notificação, para onde a Cielo enviará uma notificação sobre o status da transação.

**Comment by netojoaobatista** [comment]
Luís, o recurso foi implementado; você pode definir a URL de retorno durante a integração, utilizando o objeto `Options`.`ReturnUrl`:

```json
"Options": {
    "ReturnUrl": "http://sua-url-de-retorno/"
}
```
@1060486
