### ISSUE TITLE
Problemas integração PHP

### ISSUE THREAD

**Issue by svfelipe** [DeveloperCielo/Checkout-Cielo#2]
Bom dia,

Estamos com problemas para integrar usando o Checkout Cielo com código PHP que esta no manual, segue o código, só não funciona em nos servidores padrão da LocaWeb, local funciona bem, e o mesmo não tem nenhum problema com o cURL, existe algo a ser verificado ou mudanças na configuração do servidor?

Problema: cUrl error (#51): SSL: certificate subject name 'www.meucheckout.com.br' does not match target host name ‘cieloecommerce.cielo.com.br'

$order = new stdClass();
$order->OrderNumber = '2';
$order->SoftDescriptor = 'Corujinha';
$order->Cart = new stdClass();
$order->Cart->Discount = new stdClass();
$order->Cart->Discount->Type = 'Percent';
$order->Cart->Discount->Value = 0;
$order->Cart->Items = array();
$order->Cart->Items[0] = new stdClass();
$order->Cart->Items[0]->Name = 'Produto Teste 2';
$order->Cart->Items[0]->Description = 'Descrição do produto teste 2';
$order->Cart->Items[0]->UnitPrice = 100;
$order->Cart->Items[0]->Quantity = 1;
$order->Cart->Items[0]->Type = 'Asset';
$order->Cart->Items[0]->Sku = '18823331111';
$order->Cart->Items[0]->Weight = 200;
$order->Shipping = new stdClass();
$order->Shipping->Type = 'FixedAmount';
$order->Shipping->SourceZipCode = '';
$order->Shipping->TargetZipCode = '11000000';
$order->Shipping->Address = new stdClass();
$order->Shipping->Address->Street = 'Endereço de entrega';
$order->Shipping->Address->Number = '123';
$order->Shipping->Address->Complement = '';
$order->Shipping->Address->District = '---';
$order->Shipping->Address->City = 'Cidade da entrega';
$order->Shipping->Address->State = 'SP';
$order->Shipping->Services = array();
$order->Shipping->Services[0] = new stdClass();
$order->Shipping->Services[0]->Name = 'Frete';
$order->Shipping->Services[0]->Price = 123;
$order->Shipping->Services[0]->DeadLine = 0;
$order->Payment = new stdClass();
$order->Payment->BoletoDiscount = 0;
$order->Payment->DebitDiscount = 0;
$order->Customer = new stdClass();
$order->Customer->Identity = 11111111111;
$order->Customer->FullName = 'Fulano Comprador da Silva';
$order->Customer->Email = 'fulano@email.com';
$order->Customer->Phone = '11999999999';
$order->Options = new stdClass();
$order->Options->AntifraudEnabled = false;

$curl = curl_init();

curl_setopt($curl, CURLOPT_URL, 'https://cieloecommerce.cielo.com.br/api/public/v1/orders');
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_VERBOSE, true);
curl_setopt($curl, CURLOPT_SSLVERSION, 4);
curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($order));
curl_setopt($curl, CURLOPT_HTTPHEADER, array(
    'MerchantId: 00000000-00000000-00000000',
    'Content-Type: application/json'
));

$response = curl_exec($curl);

if ($response === FALSE) {
    printf("cUrl error (#%d): %s<br>\n", curl_errno($curl),
           htmlspecialchars(curl_error($curl)));
}

curl_close($curl);

$json = json_decode($response);
print_r($json); 

Obrigado,

Felipe Vieira

**Comment by svfelipe** [comment]
Pessoal Resolvido, recomendo que atualizem a documentação, para adicionar a linha:
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
Vocês estão usando 2 hosts diferentes...

**Comment by drupalista-br** [comment]
O cURL é problemático. Dê uma olhada em minha biblioteca em https://github.com/drupalista-br/CheckoutCielo-Library

Na biblioteca eu uso o [httpful](https://github.com/nategood/httpful) ao invés do cURL.
