### ISSUE TITLE
Consulta de transacção

### ISSUE THREAD

**Issue by luisjorgeegds** [DeveloperCielo/Checkout-Cielo#20]
Boa tarde,

Imaginando que o vosso POST a informar o estado de uma transação deu algum erro temporário do nosso lado, como poderemos ter acesso ao estado da mesma?

Seria possível que implementassem uma novo método, em que nos permitesse consultar o estado de uma determinada transação?

Obrigado.

Cumprimentos,
Luís Jorge

**Comment by netojoaobatista** [comment]
Esse recurso já foi implementado; veja: [Mudança de status via consulta](https://developercielo.github.io/Checkout-Cielo/#mudança-de-status-via-consulta)

**Comment by luisjorgeegds** [comment]
E como é feito pedido para essas situações?

**Comment by pvbinatto** [comment]
Não encontrei nenhum exemplo de consulta status da transação por código da loja. Ainda não foi implementado para o checkout?

**Comment by TCGV** [comment]
Pessoal, a URL de consulta, pelo o que diz o manual de checkout, é devolvida na [notificação da transação](https://developercielo.github.io/Checkout-Cielo/#notificação-de-transação):

> Parâmetro: URL
> Descrição: URL com os dados necessários para realizar a busca dos dados da transação.

Ou seja, se ocorrer um erro temporário na integração que impossibilite o recebimento do POST, me parece que não saberemos qual URL consultar!

**Comment by TCGV** [comment]
Olá novamente pessoal. Após alguns testes pude constatar que a URL de consulta, retornada na notificação de transação, segue este formato:

> https://cieloecommerce.cielo.com.br/api/public/v1/orders/{MerchantId}/{OrderNumber}

Eu agradeceira se alguém da Cielo puder confirmar que este formato é seguro para uso em produção, e que não sofrerá alterações.

**Comment by TCGV** [comment]
Eu de novo!

Gostaria de informar que, caso o formato da URL de consulta do pedido indicado acima seja válido em produção para todos os "MerchantIds" e "OrderNumbers" isto pode se tornar uma vulnerabilidade para sistemas que gerem "OrderNumbers" previsíveis.

Dado que a URL de consulta não requer autenticação para ser acessada, qualquer um poderá usar um gerador de requisições HTTP para obter o histórico de pagamentos dos sistemas que possuam tais "OrderNumbers" previsíveis. Segue exemplo simples para um sistema que utiliza identificadores incrementais:

>https://cieloecommerce.cielo.com.br/api/public/v1/orders/{MerchantId}/1
>https://cieloecommerce.cielo.com.br/api/public/v1/orders/{MerchantId}/2
>https://cieloecommerce.cielo.com.br/api/public/v1/orders/{MerchantId}/3
>https://cieloecommerce.cielo.com.br/api/public/v1/orders/{MerchantId}/4

E assim por diante.
