### ISSUE TITLE
Mudança de status via consulta

### ISSUE THREAD

**Issue by luisjorgeegds** [DeveloperCielo/Checkout-Cielo#21]
Boa tarde,

Podem ajudar a perceber como funciona este pedido de mudança de status?

E como é feito o pedido para essas situações? Podem enviar alguns exemplos do pedido?

Obrigado.

Cumprimentos,
Luís Jorge

**Comment by luisjorgeegds** [comment]
Boa tarde,

Alguma novidade?

Cumprimentos,
Luís Jorge

**Comment by netojoaobatista** [comment]
Quando sua aplicação receber `POST` com a notificação, a URL de consulta será enviada; basta fazer um `GET` nessa URL para obter os dados da transação, como descrito em [Notificação de transação](https://developercielo.github.io/Checkout-Cielo/#notificação-de-transação)

**Comment by luisjorgeegds** [comment]
Mas acontece que quando fazem o POST, por algum motivo temporário o nosso sistema pode estar em baixo. Nesse caso como sabemos qual o URL que devemos fazer GET?

**Comment by netojoaobatista** [comment]
Se sua aplicação não conseguir, por algum motivo temporário, receber a notificação, o Checkout Cielo tentará novamente, por 3 vezes, em intervalos de 1 hora. Caso mesmo após as 3 tentativas, uma a cada hora, o servidor continue não respondendo, o Checkout enviará um email para o responsável pela loja para avisar sobre a mudança de status.

**Comment by flaviosilvalourenco** [comment]
Sei que o post é antigo, mas estava na mesma situação então descobri que para fazer a consulta da transação na Cielo basta utilizar a URL de post da cielo + MerchantId + order_number.  Abaixo um exemplo da url:

https://cieloecommerce.cielo.com.br/api/public/v1/orders/abc12345-678d-7b21-8f30-123e456a789f/P147
