### ISSUE TITLE
Falha na tentativa de envio do POST de mudança de status - Erro 406

### ISSUE THREAD

**Issue by tiagomaker** [DeveloperCielo/Checkout-Cielo#22]
Olá, alguém já teve esse problema de não conseguir receber o POST de mudança de status com esse erro 406?

O código do arquivo retorno_cielo_status.php

`if(isset($_POST['order_number'])){
  echo '<status>OK</status>';
}`

Falha na tentativa de envio do POST de mudança de status [https://cieloecommerce.cielo.com.br]
Dados do pedido
Número do pedido	3bb47abb30b747cc98188609053cbe80
URL de mudança de status	http://dipastacaxias.com.br/alteracoes/includes/retorno_cielo_status.php
Código de status HTTP	406
Conteúdo do Post
checkout_cielo_order_number	3bb47abb30b747cc98188609053cbe80
amount	4770
order_number	49
payment_status	1
test_transaction	False

**Comment by netojoaobatista** [comment]
Verifique nos logs de seu servidor se há alguma informação. Além disso, acessei sua URL pelo browser - que é uma requisição GET - e obtive a saída *OK*, o que é inesperado. Seu código continua o mesmo?

**Comment by tiagomaker** [comment]
Cara, não tinha problema nenhum com o código, meu servidor (hostgator) estava bloqueando isso, não sei de que forma. Entrei em contato com o suporte e resolveram em 1 minuto o que eu estava tentando fazer haviam 3 horas. Mas obrigado pelo suporte.

**Comment by netojoaobatista** [comment]
Legal, @tiagomaker!

Vou fechar essa thread então; caso tenha outra dúvida, por favor, abra uma nova thread.

:smile:
