### ISSUE TITLE
Ajuda em uma requisição

### ISSUE THREAD

**Issue by tioago** [DeveloperCielo/Checkout-Cielo#23]
Bom dia,

Estou desenvolvendo uma aplicação que se integra com o Checkout-Cielo no Android usando a API 3.0 mas sem usar a comunicação já criada, pois esta apresentou problema com a comunicação do meu servidor, mas ainda assim estou com um problema, ao criar uma venda de boleto, ele não reconhece o Payment envolvido na venda. Faz 2 semanas que procuro uma solução e o sistema só me retorna: "119: At least one Payment is required". Eu criei um json Object para enviar pelo Body da requisição, com as informações e ele me retorna o erro citado. O mesmo objeto no Postman, responde corretamente. (O objeto está enviando somente o necessário para uma venda simples via boleto). Segue um pouco do código:

Requisição:

```
    JSONObject jsonObject = new JSONObject();

    CreateSellBoleto create = new CreateSellBoleto();
    create.MerchantOrderId = merhantOrderId;

    PaymentBoleto payment = new PaymentBoleto();
    payment.Type = paymentType;
    payment.Amount = paymentAmount;
    payment.Provider = paymentProvider;
    create.Payment = payment;

    com.br.hipercor.model.cielo.Customer cust = new com.br.hipercor.model.cielo.Customer(customerName);
    create.customer = cust;

    Log.i(TAG,create.MerchantOrderId);
    Log.i(TAG,create.customer.getName());
    Log.i(TAG,create.Payment.Amount);

    Gson gson = new Gson();
    String json = gson.toJson(create);

    Log.i(TAG,json + " <<< FULL OBJECT");
    try {
        jsonObject = new JSONObject(json);
    } catch (JSONException e) {
        e.printStackTrace();
    }
    Log.i(TAG,jsonObject + " <<< OBJECT SENT");

    EventBus.getDefault().post(new ShowDialogEvent());
    mServiceCielo.getApiServiceCielo().createBoleto(jsonObject, new Callback<ResponseCreateBoleto>() {
        @Override
        public void success(ResponseCreateBoleto responseCreateBoleto, Response response) {
            EventBus.getDefault().post(new HideDialogEvent());
            EventBus.getDefault().post(new CreateBoletoEvent(responseCreateBoleto));
        }

        @Override
        public void failure(RetrofitError error) {
            EventBus.getDefault().post(new HideDialogEvent());
            EventBus.getDefault().post(new FailedEvent(error));

            try {
                com.squareup.okhttp.Response response = client.newCall(request).execute();

                EventBus.getDefault().post(new CreateBoletoPostman(response));
            } catch (IOException e) {
                e.printStackTrace();
            }

        }
    });
```

O objeto enviado fica assim: 
{"MerchantOrderId":"336","Payment":{"Amount":"25","Provider":"Bradesco","Type":"Boleto"},"Customer":{"Name":"Tiago Alencar"}}

Como disse, se enviar esse objeto pelo postman, com os headers setados, ele funciona, no Android Studio enviando pelo body, com os headers, não funciona. Pode me dar uma ajuda com isso?

**Comment by netojoaobatista** [comment]
Checkout-Cielo e API 3.0 são duas APIs diferentes, com duas documentações diferentes e métodos de integração completamente diferentes.

* [Manual do Checkout](https://developercielo.github.io/Checkout-Cielo/)
* [Manual da API 3.0](https://developercielo.github.io/Webservice-3.0/)
