### ISSUE TITLE
Como utilizar os códigos?

### ISSUE THREAD

**Issue by hicarocastro** [DeveloperCielo/Checkout-Cielo#25]
A linguagem do meu site é ASP Clássico, como faço para realizar a integração?

**Comment by netojoaobatista** [comment]
O [Manual do Checkout Cielo](https://developercielo.github.io/Checkout-Cielo)  descreve todo o processo de integração.

:smile:

**Comment by hicarocastro** [comment]
Não para linguagem ASP, tem algum exemplo?

**Comment by netojoaobatista** [comment]
Para ASP clássico, não. Só em C# para ser usado com ASP.NET.

**Comment by hicarocastro** [comment]
Pois, não tem como fazer no ASP?

**Comment by netojoaobatista** [comment]
Você consegue implementar em qualquer tecnologia que esteja trabalhando, só seguir o fluxo de integração descrito no [Manual do Checkout Cielo](https://developercielo.github.io/Checkout-Cielo/).

**Comment by hicarocastro** [comment]
Já li o manual umas 3 vezes inclusive tem coisa desnecessária no manual, estou tentando integrar Cielo Checkout e o manual tem um pedaço enorme que falar de certificado SSL que e desnecessário para o meu caso, confirmei por telefone.

Preciso de um ponto de partida, inicialmente conseguir postar os campos escritos em JSON em ASP Clássico, mas não estou sabendo como fazer isso.
