### ISSUE TITLE
Exemplo PHP | Usar httpful ao invés de curl

### ISSUE THREAD

**Issue by drupalista-br** [DeveloperCielo/Checkout-Cielo#3]
Já tive muita dor de cabeça com o curl no passado. Uma solução mais simples de usar e que não me causa transtornos é o [httpful](https://github.com/nategood/httpful).

Eu escrevei uma biblioteca que implementa o exemplo do manual da Cielo em https://github.com/drupalista-br/CheckoutCielo-Library

Dê uma olhada no método `request_new_transaction()`  em https://github.com/drupalista-br/CheckoutCielo-Library/blob/2.x-dev/src/Checkout/Transaction.php e note o quanto é mais simples o uso do httpful.

**Comment by netojoaobatista** [comment]
Interessante, @drupalista-br!

Posso fazer um fork do seu código de exemplo para o repositório da Cielo, se você permitir. Assim outros desenvolvedores terão a oportunidade de escolher a forma de implementação mais adequada para seus projetos.

:smile:

**Comment by drupalista-br** [comment]
Olá @netojoaobatista,

Sim, por favor, faça o fork sim. Abraço!

Obrigado.

**Comment by netojoaobatista** [comment]
@drupalista-br,

Fiz o fork do seu repositório. Também criei um time aqui no perfil da Cielo, dei permissões de gravação ao repositório e tomei a liberdade de adicioná-lo ao time. Com isso você conseguirá fazer push diretamente para o repositório da Cielo, fazer merge de PRs, etc.

:smile:

**Comment by drupalista-br** [comment]
Maravilha,

Eu aceite o Join Request e quando eu fizer novos commits no meu repositório, autorizarei também os Pull Requests no seu fork.

Abraço.
