### ISSUE TITLE
Questionamento

### ISSUE THREAD

**Issue by CesarBalzer** [DeveloperCielo/Checkout-Cielo#30]
Estou com uma questão a respeito da falta de um item de apoio para segurança do checkout cielo para os usuários da plataforma.
Quando é gerada uma transação é enviada à cielo, esta resposta me retorna a url de pagamento, o profile e a versão, que não acho útil para usar em nenhuma validação no meu sistema, a não ser para saber se a transação deu certo ou não;
Agora após o pagamento do cliente no site da cielo, poderá retornar o post de notificação, e mudança de status como descrito no manual;
Neste momento que o sistema captura o post, como poderia ser feita uma validação segura pra saber exatamente se este post recebido pelo sistema é realmente da cielo?
Existe alguma forma de validar isso?
Somente consigo gerar alguma validação através do campo order_number, que é criado quando faço o envio da transação no primeiro momento, para retornar a url de pagamento.
E através desse código que faço toda a verificação em meu sistema.
Agora digamos que algum indivíduo maldoso, de alguma forma descobriu a url, e por acaso tente fazer um post fake para minha url de retorno cadastrada na cielo, para forjar como se tivesse pago. Se neste momento do retorno somente possuo o meu código gerado(order_number) que foi enviado a cielo, como posso me assegurar que este post que recebi veio realmente da Cielo e não de um atacante...

**Comment by netojoaobatista** [comment]
Veja: [Mudança de status via consulta](https://developercielo.github.io/Checkout-Cielo/#mudança-de-status-via-consulta)

**Comment by CesarBalzer** [comment]
Mas então o plano Checkout Cielo contratado não cobre esta opção com descreve no popover da informação ao lado das opções de Tipo de Notificação:
Receber como POST   Buscar como JSON 
Essa é uma opção de mudança no fluxo de recebimento de alerta das suas vendas. A opção via json funciona apenas para integração via API. Consulte seu desenvolvedor para essa opção. Informações: https://developercielo.github.io/Checkout-Cielo/#notificação-de-transação. 
Eu teria que contratar mais o plano API e-Commerce Cielo?

Obs: Tipo de "Noticação", está errado o label no painel, onde seria Notificação.

**Comment by CesarBalzer** [comment]
Desculpe pela falta de entendimento no item que mencionou na documentação, estava ali desde o começo.
Vou deixar documentado aqui caso alguém precise e não tenha entendido assim como eu.
Quando retornar o JSON da notificação, por padrão a Cielo envia junto nos parâmetros a URL, onde no sistema será dado o GET com essa URL vinda na notificação, assim sabemos que a transação realmente existe na Cielo e que o POST recebido foi realmente vindo da Cielo.
