### ISSUE TITLE
O Servidor remoto retornou erro: (400) Solicitação Incorreta

### ISSUE THREAD

**Issue by felipeejunges** [DeveloperCielo/Checkout-Cielo#31]
Olá, estou tentando desenvolver a comunicação com a API 3.0 com VB.NET, mas na parte de comunicação com o servidor, estou tendo problemas para transação simples.

Tentei dessa forma:
`Public Function postDados2(json As String, baseUrl As String, postUrl As String, merchant As Merchant) As String
        Dim urlPost As String = baseUrl & postUrl
        Dim jsonVolta As String

        Try
            Dim request As WebRequest = WebRequest.Create(urlPost)
            request.Method = "POST"
            request.ContentType = "application/json"
            request.Headers("MerchantId") = merchant.id

            Using writer = New StreamWriter(request.GetRequestStream())
                writer.Write(json)
                writer.Close()
            End Using

            Dim response As HttpWebResponse = DirectCast(request.GetResponse(), HttpWebResponse)
            jsonVolta = response.ToString
        Catch ex As Exception
            Throw ex
        End Try

        Return jsonVolta
    End Function`

E dessa forma: 
`    Public Function postDados(json As String, baseUrl As String, postUrl As String) As String
        Dim urlPost As String = baseUrl & postUrl

        Dim webClient As New WebClient()
        Dim resByte As Byte()
        Dim jsonVolta As String
        Dim reqByte() As Byte

        reqByte = Encoding.Default.GetBytes(json)
        Try
            webClient.Headers("content-type") = "application/json"
            reqByte = Encoding.Default.GetBytes(json)
            jsonVolta = webClient.UploadString(urlPost, json)
            resByte = webClient.UploadData(urlPost, "post", reqByte)
            jsonVolta = Encoding.Default.GetString(resByte)
            webClient.Dispose()
        Catch ex As Exception
            Throw ex
        End Try

        Return jsonVolta
    End Function`

Valor urlPost: https://apisandbox.cieloecommerce.cielo.com.br/1/sales/
Valor Json: 
> {""MerchantOrderId"":""1234123"",""Customer"":{""name"":""teste""},""Payment"":{""Type"":""CreditCard"",""Amount"":1.0,""Installments"":1,""SoftDescriptor"":"""",""CreditCard"":{""CardNumber"":""12312312"",""Holder"":""teste"",""ExpirationDate"":""2022-12-12"",""SecurityCode"":""1212"",""Brand"":""Visa""}}}

PS: No Exemplo postDados, eu coloco a MerchantId e Key dentro acima do MerchantOrderId e não no Header como no exemplo postDados2

**Comment by netojoaobatista** [comment]
@felipeejunges, esse repositório é sobre o Checkout; se sua integração é com a 3.0, por favor, abra a issue no [repositório da 3.0](https://github.com/DeveloperCielo/Webservice-3.0/issues).

De qualquer forma, se o conteúdo do seu json é esse que você enviou aí, então o json é inválido; arrume seu json para ficar assim:

```json
{"MerchantOrderId":"1234123","Customer":{"name":"teste"},"Payment":{"Type":"CreditCard","Amount":1.0,"Installments":1,"SoftDescriptor":"","CreditCard":{"CardNumber":"12312312","Holder":"teste","ExpirationDate":"2022-12-12","SecurityCode":"1212","Brand":"Visa"}}}
```

**Comment by felipeejunges** [comment]
Abrirei lá, mas não entendi o erro, seria as aspas a mais ? Porque estou gerando o json do objeto pelo newtonsoft, ele faz isso de forma automatica.

**Comment by netojoaobatista** [comment]
> seria as aspas a mais 

Exato; o json não tem essa aspas a mais aí; se está vindo com as aspas dobradas, então estragou o json. Mas já que abriu lá, vou fechar essa issue aqui e seguimos por lá.
