### ISSUE TITLE
Parâmetro de Notificação/Update 'payment_status' | Lista com descrições dos códigos

### ISSUE THREAD

**Issue by drupalista-br** [DeveloperCielo/Checkout-Cielo#4]
Olá,

O manual da modalidade CheckoutCielo diz que o parâmetro de notificação/update ['payment_status'](http://developercielo.github.io/Checkout-Cielo/#url-de-notificação) informará o código numerico do status da transação.

Eu vasculhei o referido manual do começo ao fim em busca de uma lista com as descrições dos códigos de Status, mas NÃO encontrei. Então eu presumi que as descrições dos [Status das Transações](https://developercielo.github.io/Webservice-1.5/#status-das-transações) da modalidade Webservice seriam as mesmas para a modalidade CheckoutCielo.

Aparentemente a minha presunção NÃO estava correta, pois os meus testes com a modalidade CheckoutCielo estão me enviando o código 7. Note que NÃO há o código 7 em [Status das Transações](https://developercielo.github.io/Webservice-1.5/#status-das-transações).

Poderia por favor me enviar a lista com as descrições dos códigos dos Status das Transações para a modalidade CheckoutCielo para que eu possa corrigir as constantes em https://github.com/drupalista-br/CheckoutCielo-Library/blob/2.x-dev/src/Checkout/Transaction.php.

Regards,

**Comment by netojoaobatista** [comment]
@drupalista-br, bom dia!

Vou adicionar a informação ao manual, mas até estar publicado, seguem os status:

|Valor|Descrição|
|------|-------------|
|1|Pendente (Para todos os meios de pagamento)|
|2|Pago (Para todos os meios de pagamento)|
|3|Negado (Somente para Cartão Crédito)|
|5|Cancelado (Para cartões de crédito)|
|6|Não Finalizado (Todos os meios de pagamento)|
|7|Autorizado (somente para Cartão de Crédito)|

**Comment by drupalista-br** [comment]
Obrigado.

**Comment by netojoaobatista** [comment]
A documentação já foi atualizada: [Checkout Cielo - payment_status](https://developercielo.github.io/Checkout-Cielo/#url-de-mudança-de-status)

**Comment by drupalista-br** [comment]
Constantes foram corrigidas https://github.com/DeveloperCielo/CheckoutCielo-Library/blob/2.x-dev/src/Checkout/Transaction.php
