### ISSUE TITLE
Parâmetro 'payment_status' | Notificação/Update - Valor 4

### ISSUE THREAD

**Issue by drupalista-br** [DeveloperCielo/Checkout-Cielo#5]
Olá,

Há alguns dias atrás eu exclui, no Backoffice da Cielo em ambiente de teste, todos os pedidos que eu fizera enquanto escrevia a integração com o [Drupal Commece](https://www.drupal.org/project/commerce_cielo).

Hoje, no decorrer do dia, o log do meu website vem registrando o update do Status de Pagamento, pelo POST do sistema da Cielo, referente à aqueles pedidos antigos que eu exclui no BackOffice.

O log aponta falha no update do Status de Pagamento porque o valor enviado para o parâmetro 'payment_status' é 4. O valor 4 é inexperado, pois ele não consta na lista em [Status de Pagamento](https://developercielo.github.io/Checkout-Cielo/#payment_status) do manual.

Poderia por favor confirmar se o valor 4 é válido e qual a descrição dele.

**Comment by netojoaobatista** [comment]
`payment_status`=4 significa expirado:

O parâmetro `payment_status` poderá vir com um dos seguintes valores:

|Valor|Descrição|
|------|-------------|
|1|Pendente (Para todos os meios de pagamento)|
|2|Pago (Para todos os meios de pagamento)|
|3|Negado (Somente para Cartão Crédito)|
|4|Expirado (Cartões de Crédito e Boleto)|
|5|Cancelado (Para cartões de crédito)|
|6|Não Finalizado (Todos os meios de pagamento)|
|7|Autorizado (somente para Cartão de Crédito)|
|8|Chargeback (somente para Cartão de Crédito)|
