### ISSUE TITLE
Timed out no checkout

### ISSUE THREAD

**Issue by arenasam** [DeveloperCielo/Checkout-Cielo#6]
Bom dia, 
estou apanhando para a integração do checkout com zend 2, 
consigo acessar outras páginas através do cUrl, já liguei na central, minha conta está configurada corretamente, entretanto continuo recebendo o erro:

Error in cURL request: Operation timed out after 30015 milliseconds with 0 bytes received

Alguém pode me ajudar? estou completamente perdido, não recebo nenhum detalhe do que pode estar acontecendo...

Código:

<?php 
$view = new ViewModel();
        $view->setTerminal(true);

        $sessao = new Container();
        $idInscricao = 67;//$sessao->offsetGet('inscricao');
        //pesquisar inscrição
        $serviceInscricao = $this->getServiceLocator()->get('Inscricao');
        $inscricao = $serviceInscricao->getInscricaoById($idInscricao);

        $order = new \stdClass();
        $order->OrderNumber = $inscricao->id;
        $order->SoftDescriptor = 'Time Eventos';
        $order->Cart = new \stdClass();
        $order->Cart->Items = array();
        $order->Cart->Items[0] = new \stdClass();
        $order->Cart->Items[0]->Name = $inscricao->nome_evento;
        $valorTotal = str_replace('.', '', $inscricao->valor_total);
        $order->Cart->Items[0]->UnitPrice = 100;//$valorTotal;
        $order->Cart->Items[0]->Quantity = 1;
        $order->Cart->Items[0]->Type = 'Service';
        $order->Shipping = new \stdClass();
        $order->Shipping->Type = 'WithoutShipping';
        /*$order->Shipping->SourceZipCode = '14400000';
        $order->Shipping->TargetZipCode = '11000000';
        $order->Shipping->Address = new stdClass();
        $order->Shipping->Address->Street = 'Endereço de entrega';
        $order->Shipping->Address->Number = '123';
        $order->Shipping->Address->Complement = '';
        $order->Shipping->Address->District = 'Bairro da entrega';
        $order->Shipping->Address->City = 'Cidade da entrega';
        $order->Shipping->Address->State = 'SP';
        $order->Shipping->Services = array();
        $order->Shipping->Services[0] = new stdClass();
        $order->Shipping->Services[0]->Name = 'Serviço de frete';
        $order->Shipping->Services[0]->Price = 123;
        $order->Shipping->Services[0]->DeadLine = 15;*/
        $order->Payment = new \stdClass();
        $order->Payment->BoletoDiscount = 0;
        $order->Payment->DebitDiscount = 0;
        $order->Customer = new \stdClass();
        $order->Customer->Identity = 01473651638;
        $order->Customer->FullName = 'cliente '.$inscricao->nome_completo;
        $order->Customer->Email = $inscricao->email_cliente.'email';
        $order->Options = new \stdClass();
        $order->Options->AntifraudEnabled = true;

        

        $request = new Request();
        $request->setUri('https://cieloecommerce.cielo.com.br/api/public/v1/orders');
        $request->setMethod('POST');

        $client = new Client();
        $client->setOptions(array('timeout' => 30));
        $adapter = new Curl();
        $client->setAdapter($adapter);

        

        $adapter->setOptions(array(
            'curloptions' => array(
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => json_encode($order),
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_HTTPHEADER => array(
                        'MerchantId: 00000000-0000-0000-0000-000000000000',
                        'Content-Type: application/json'
                    )

            )
        ));

        $response = $client->dispatch($request);
        $response = json_decode($response->getBody());
        print_r($response);
        die();
?>

Print dos parâmetros:

object(stdClass)[404]
  public 'OrderNumber' => string '67' (length=2)
  public 'SoftDescriptor' => string 'Time Eventos' (length=12)
  public 'Cart' => 
    object(stdClass)[403]
      public 'Items' => 
        array (size=1)
          0 => 
            object(stdClass)[393]
              ...
  public 'Shipping' => 
    object(stdClass)[401]
      public 'Type' => string 'WithoutShipping' (length=15)
  public 'Payment' => 
    object(stdClass)[394]
      public 'BoletoDiscount' => int 0
      public 'DebitDiscount' => int 0
  public 'Customer' => 
    object(stdClass)[405]
      public 'Identity' => string '01473651638' (length=11)
      public 'FullName' => string 'cliente Vinicius Silva' (length=22)
      public 'Email' => string 'vinicius.s.dornelas@gmail.comemail' (length=34)
  public 'Options' => 
    object(stdClass)[406]
      public 'AntifraudEnabled' => boolean true

---- CART:

object(stdClass)[403]
  public 'Items' => 
    array (size=1)
      0 => 
        object(stdClass)[393]
          public 'Name' => string 'Evento de teste 01' (length=18)
          public 'UnitPrice' => int 100
          public 'Quantity' => int 1
          public 'Type' => string 'Service' (length=7)

**Comment by netojoaobatista** [comment]
@arenasam, você está com o certificado da Cielo instalado aí?

Esse timeout pode ser problemas com o TLS.

**Comment by arenasam** [comment]
@netojoaobatista  que certificado? 
segui o tutorial:
 http://developercielo.github.io/Checkout-Cielo/?php#carrinho-de-compras

até então estava pensando que seria uma requisição http...

pode me passar o link do certificado? se tiver algum titorial tbm vai ajudar =)

Obrigado!

**Comment by netojoaobatista** [comment]
Seção do manual que trata sobre o certificado: [Certificado Extended Validation](https://developercielo.github.io/Checkout-Cielo/?php#certificado-extended-validation)

Também verifique a versão da cURL que está utilizando e a versão padrão configurada. Após verificar o certificado, faça o seguinte ajuste em seu código:

```php
$adapter->setOptions(array(
    'curloptions' => array(
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => json_encode($order),
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1,
        CURLOPT_HTTPHEADER => array(
                'MerchantId: 00000000-0000-0000-0000-000000000000',
                'Content-Type: application/json'
            )

    )
));
```

Apenas para garantir, você está definindo corretamente seu `MerchantId`, né?

**Comment by arenasam** [comment]
Boa tarde, 
consegui resolver, na verdade não estava enviando nenhum parâmetro =/.
O problema era que o adaptador no Zend não aceita json como parâmetro,
ele exige um array. Outro problema é que eu não posso acessar as opções 
CURLOPT_POST e CURLOPT_POSTFIELDS diretamente. 


Enfim, consegui fazer a integração com o layout antigo, segue o 
código:

//CONTROLLER
        $sessao = new Container();
        $idInscricao = 67;//$sessao->offsetGet('inscricao');
        //pesquisar inscrição
        $serviceInscricao = $this->getServiceLocator()->get('Inscricao');
        $inscricao = $serviceInscricao->getInscricaoById($idInscricao);

        $order = array(
                'merchant_id'       =>  '00000000-0000-0000-0000-000000000000',
                'order_number'      =>  $inscricao->id,
                'shipping_type'     => 5,
                'cart_1_name'       => $inscricao->nome_evento,
                'cart_1_unitprice'  => 100,
                'cart_1_quantity'   => 1,
                'cart_1_type'       => 3,
                'customer_name'     => $inscricao->nome_completo,
                'customer_identity' => '01473651638',
                'customer_email'    =>  $inscricao->email_cliente
            );

        $client = new Client('https://cieloecommerce.cielo.com.br/Transactional/Order/Index');
         $client->setMethod('POST');
        $client->setOptions(array('timeout' => 30));
        $adapter = new Curl();
        $client->setAdapter($adapter);

        $client->setParameterPost($order);

        $adapter->setOptions(array(
            'curloptions' => array(
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => 0
            )
        ));

        $response = $client->send($client->getRequest());
        $response = $response->getBody();
        
        $view = new ViewModel(array('html' => $response));
        $view->setTerminal(true);
        return $view;

//VIEW
<?php 
	echo $html;
?>

É necessário criar o arquivo Transactional/Scripts/jquery-1.7.1.min.js 

Obrigado pela ajuda @netojoaobatista
