### ISSUE TITLE
RECUPERAÇÃO DE DADOS ENVIADOS PELO CHECKOUT

### ISSUE THREAD

**Issue by robeliojunior84** [DeveloperCielo/Checkout-Cielo#7]
Olá, boa tarde!
Gostaria de esclarecer uma dúvida. Quando o cliente sai da minha loja e é direcionado ao CheckOut Cielo para efetuar o pagamento, ele é direcionado para a página que eu configurei na minha URL de Retorno. Eu gostaria de saber como eu faço para recuperar os dados enviados pelo formulário. Exemplo:
Quando eu envio o nome do cliente, ele enviaria o "customer_name" em método POST, para eu recuperar, eu iria declarar a variável:
$customer_name = $_POST["customer_name"];

E para exibir a mesma, eu iria colocar o:

echo $customer_name;

Contudo, fazendo isso, retorna em branco, como se não estivesse enviando o parâmetro. Como fazer para recuperar essas variáveis enviadas pelo formulário do CheckOut Cielo?

Att,
Junior
E-mail: junior@dimarkdigital.com.br

**Comment by netojoaobatista** [comment]
@robeliojunior84, no retorno do seu cliente para a URL de Retorno, não é enviado nenhum dado desse tipo. Por isso que você não consegue recuperar a informação utilizando a super global `$_POST`.

Essas informações são enviadas para sua aplicação para a URL cadastrada em URL de Notificação e as mudanças de status para a URL cadastrada em URL de Mudança de Status.

**Comment by robeliojunior84** [comment]
@netojoaobatista neste caso então eu não consigo de forma alguma recuperar estes dados em nenhuma tela? No campo URL de Notificação eu coloquei um endereço, neste endereço eu não consigo fazer a recuperação dos dados não?

**Comment by netojoaobatista** [comment]
Na URL de Notificação você consegue. No manual é descrito quais variáveis são enviadas e seus significados: [Manual Checkout Cielo - URL de Notificação](https://developercielo.github.io/Checkout-Cielo/#url-de-notificação)

**Comment by robeliojunior84** [comment]
@netojoaobatista eu fiz isso, no caso a minha URL de Notificação hoje, está cadastrada a URL https://www.viverbike.com.br/testeretorno.php 

Nesta página eu estou tentando, por exemplo, recuperar o nome do cliente, usando o seguinte código:

<?php
$customer_name =  $_POST["customer_name"];

echo $customer_name;
?>

Seria desta forma mesmo?

**Comment by netojoaobatista** [comment]
Você não verá esse `echo`, uma vez que o envio da notificação é assíncrono. É o servidor da Cielo enviando a notificação para o servidor da sua aplicação. Você não verá essa informação no browser. Será necessário processar e gravar as informações numa base de dados e proceder com a liberação do pedido do seu cliente.

**Comment by robeliojunior84** [comment]
@netojoaobatista entendi Neto, estarei fazendo aqui então a tela para gravação em banco de dados.
Obrigado.

**Comment by netojoaobatista** [comment]
:smile:

**Comment by robeliojunior84** [comment]
@netojoaobatista Neste caso, pelo que vi, ele não recupera os dados da compra, como produto, quantidade, etc, somente as informações de pagto e entrega?

Att.
