### ISSUE TITLE
RECUPERAÇÃO DE DADOS ENVIADOS PELO CHECKOUT

### ISSUE THREAD

**Issue by robeliojunior84** [DeveloperCielo/Checkout-Cielo#8]
@netojoaobatista Neto, pelo que vi então, ele não recupera os dados de vendas, como produto e quantidade, somente os outros dados como pagto e dados de entrega, certo?

**Comment by netojoaobatista** [comment]
Junto aos dados da notificação você receberá o campo `order_number`, que é o número do pedido que você enviou para a Cielo. Você deve ter registrado na sua base de dados o pedido do cliente, correto? Utilize esse campo para buscar as informações dos itens comprados e as respectivas quantidades.

**Comment by robeliojunior84** [comment]
O meu order_number não defini, deixei para a cielo mesmo definir automaticamente, mas neste caso vou coloca la para que o meu seja definido e ve se vai dar certo.

**Comment by netojoaobatista** [comment]
Nesse caso, como a Cielo não retorna os dados dos itens, se você precisar da informação na sua aplicação, você precisará gravar o pedido e os respectivos itens na sua base de dados. Lembre-se apenas que o ID do pedido deve ser **único**.

Se não enviar essa informação, você não terá como gerir o pedido em sua aplicação e a única forma de saber quais são os itens é utilizando o [BackOffice Cielo](https://developercielo.github.io/Checkout-Backoffice/).

**Comment by robeliojunior84** [comment]
Neste caso vou colocar o código para gerar o número do pedido, tenso é que não estou conseguindo desenvolver o script.. algo simples e cabeça cheia....

**Comment by kielvi** [comment]
Estou tendo a mesma dificuldade, não estou sabendo recuperar os dados da transação depois dela efetuada. Eu guardei o ID unico do pedido..
Pode dar um help em como é feito essa busca?

**Comment by netojoaobatista** [comment]
@kielvi,

Quando o cliente efetuar o pagamento no ambiente seguro da Cielo, ele será redirecionado de volta para a loja, na URL cadastrada em URL de Retorno. Essa é apenas uma URL de redirecionamento, a Cielo **não envia nenhum dado** para ela.

De forma assíncrona, uma notificação será enviada para a URL cadastrada em URL de notificação. Para essa URL, sim, serão enviados todos os dados da transação, ID único do pedido, etc. Essa URL deve responder com `<status>OK</status>` para que o serviço de notificação da Cielo saiba que você recebeu a notificação e a processou corretamente.

Também de forma assíncrona, uma notificação será enviada para a URL cadastrada em URL de Mudança de Status. Para essa URL, a Cielo enviará apenas a mudança de status de uma transação e você receberá o ID único do pedido, o status da transação e o valor total.

Todas as URLs do Checkout Cielo, seus significados, dados enviados e como a aplicação deve responder, são descritas na seção [URLs do Checkout Cielo do manual](https://developercielo.github.io/Checkout-Cielo/#urls-do-checkout-cielo)

**Comment by kielvi** [comment]
Eu entendi que a CIELO não envia nenhum dado @netojoaobatista, o que não estou entendendo como configurar esta página de mudança de status, este valor <status>OK</status> deverá estar em forma de JSON? 
Desculpe, realmente estou perdido nessa parte.

**Comment by netojoaobatista** [comment]
A URL de notificação deve apenas receber o POST de notificação e processar os dados. Ao fim do processamento, deve responder **exatamente** `<status>OK</status>` - que é um fragmento de XML.

Em PHP ficaria mais ou menos assim:

```php
<?php
if (isset($_POST['order_number'])) {
    // pesquisa o order_number na base de dados e processa o pedido
    // utilizando o restante dos dados enviados na notificação.
    $order_number = $_POST['order_number'];
    $payment_status = $_POST['payment_status'];

    // ao fim do processamento, respondo para o serviço de notificação que
    // tudo foi processado corretamente
    echo '<status>OK</status>;
}
```

Os valores possíveis do `payment_status` estão descritos no manual, na seção [payment_status](https://developercielo.github.io/Checkout-Cielo/#url-de-mudança-de-status) do manual.

**Comment by ximnes** [comment]
Olá @netojoaobatista  tentei essa solução que você fez com o isset, porém não tive exito.
Minha loja online já está 100%, só não estou recebendo dados de notificação e status.
Fiz um tópico novo, porém não sei se teve visualização.

Desde já agradeço

**Comment by TiagoGouvea** [comment]
@netojoaobatista Estou passando pelo mesmo aqui, entro nos "Detalhes do pedido" e clico nos botões azuis, para reenviar o post, porém não recebo nada. Estou logando todas as requisições que chegam na url de notificação/mudança de status em arquivo, porém, não vem post (nem get).
Estou no modo teste.
O que fazer @netojoaobatista ?

**Comment by netojoaobatista** [comment]
As URLs estão configuradas corretamente no backoffice? Verifiquem nos logs do servidor, se os dados estão chegando.
